### ISSUE TITLE
#bug carved pumpkin Spirit summoning not working

### ISSUE THREAD

**Issue by HarbingerOfCrazy** [hjake123/reactive#23] opened 2023-12-07 15:12 UTC
MC ver 1.20.1 :Summoning spirits with soul and carved pumpkins only works with the blaze.
suspected cause, from looking at the code:
candles block name is candles not candle, so it can not be found.
(suggestion: use blocktags to support modded candles?)

**Comment by hjake123** [comment] 2023-12-08 00:31
I couldn't reproduce this issue (it works for me). Are you using undyed candles and are they lit?
Either way, it should be using the block tag (I think when I made that I was unaware the block tag existed?), but it'd be good to know if it was actually not working.

**Comment by hjake123** [comment] 2023-12-08 00:45
I could have sworn I'd added "(Undyed)" to the Candle hint but it seems that didn't happen so if making the tag work is too much of a hassle I could at least clarify the instructions

**Comment by hjake123** [comment] 2023-12-08 02:03
Fixed in 7a

**Closed by hjake123** 2023-12-08 02:03 UTC
Labels: bug
