### ISSUE TITLE
Ender Rift teleportation is not always blocked by a Ferrous Crystal

### ISSUE THREAD

**Issue by wymesue** [hjake123/reactive#70] opened 2024-11-09 22:30 UTC
So i am having a problem. I want to make a linked bottle of warp. i have done this before, but this time I am having issues. (I tried multiple places).  

First: I used my skulk crucible put a hopper pointing to it,  held a ferrous crystal in offhand, quartz bottle in main hand,  then added an ender pearl in the hopper. I teleported into the crucible. 
Second: I thought I did it wrong - Followed same process same result
Third: I thought ok maybe my crystal is borked even though it shows fine. Remade ferrous crystal - Same result
Fourth: I thought ok maybe the warp solution in the crucible got corrupted or some such nonsense. Emptied Crucible added bucket of water - added warped roots until warp was at 97%. Did the hopper/pearl thing.. Same results

I am not sure what is happening. I had made one not 5 minutes before it went wonky. I have not been able to get it to work since.

**Comment by hjake123** [comment] 2024-11-09 23:11
Huh. That's very strange, it sounds like you're doing things right.

**Comment by hjake123** [comment] 2024-11-09 23:11
Are you on 1.21 or 1.20?

**Comment by hjake123** [comment] 2024-11-09 23:15
In the meantime you can use the `/reactive give_warp_bottle` command if you need the bottle immediately.

**Comment by wymesue** [comment] 2024-11-10 22:18
> Are you on 1.21 or 1.20?

We are on 1.20.1. I am on a server. The link to the modpack is https://www.curseforge.com/minecraft/modpacks/official-minecolonies-special-events

Unfortunately I can not use a command as i am not the server owner.

**Comment by hjake123** [comment] 2024-11-10 22:37
I can't seem to replicate the issue. (Also, it seems like this version of the mod has broken JEI integration with the JEI version you're using, which is unfortunate but not the cause of your issue)

**Comment by hjake123** [comment] 2024-11-10 23:42
Have you tried completely breaking the Crucible and placing it back down? Could be its data is corrupt somehow but I can't see why that'd happen. The Ferrous Crystal code I guess could also have some issue, but again it doesn't make sense...

Also try having the Ferrous Crystal somewhere else in your inventory then your offhand. The main/offhand check is separate from the whole inventory scan, but they should both work to prevent the teleportation. The other option is some server desync, where the server doesn't think you have the item, but that seems really unlikely.

**Comment by wymesue** [comment] 2024-11-12 06:39
> Have you tried completely breaking the Crucible and placing it back down? Could be its data is corrupt somehow but I can't see why that'd happen. The Ferrous Crystal code I guess could also have some issue, but again it doesn't make sense...
> 
> Also try having the Ferrous Crystal somewhere else in your inventory then your offhand. The main/offhand check is separate from the whole inventory scan, but they should both work to prevent the teleportation. The other option is some server desync, where the server doesn't think you have the item, but that seems really unlikely.

I did used three different crucibles, I was using a skulk one then i made a new one and then tried again with a different one someone else had.  I tried the ferrous in my offhand in my inventory, in my main hand. I also made a brand new ferrous crystal to see if that was the problem.  I tried using ender eyes for the warp solution, then i tried with only warped fungus. I think i've tried every variation and combination i could think of. 

Other people on the server have had the same issue so I don't think its specific to me or any items i have. 

If you want me to try something else I can.

**Comment by hjake123** [comment] 2024-11-12 09:06
> Other people on the server have had the same issue so I don't think its specific to me or any items i have.

That's... concerning.

Aha! I found the issue. If you have a LivingEntity somewhere within the Crucible range (about 12 blocks) that is sorted in the internal list earlier then you, the current routine only checks if *they* are holding a Ferrous Crystal, and then teleports the nearest entity. This, clearly is the wrong behavior, but if you move your setup somewhere there are no nearby entities, it should work.

**Comment by hjake123** [comment] 2024-11-12 09:08
I'll be patching this in the next release, but since you're on an event modpack I doubt your server would update, so hopefully this workaround is good enough.

**Comment by wymesue** [comment] 2024-11-12 23:03
You are awesome thank you! I will contact the modpack people to update it.

**Comment by hjake123** [comment] 2024-11-13 00:22
Fixed in `9l.0`

**Closed as completed by hjake123** 2024-11-13 00:22 UTC
Labels: bug
